[package]
name = "keystone-ha-defs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
kube = { version = "0.96", features = ["derive"] }
k8s-openapi = { version = "0.23", features = ["v1_30"] }
chrono = { version = "0.4", features = ["serde"] }